version: '3.5'

services:
    front-end-poc-softplan-pablo:
      container_name: front-end-softplan-pablo-container
      build: .
      ports: 
        - '4200:4200'
      command: > 
        bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"